

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - static_volume:/backend/static
      - db_volume:/backend/db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "90:90"
    depends_on:
      - backend

volumes:
  static_volume:
  db_volume:
