version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000

  web:
    build: ./frontend
    ports:
      - "5173:5173"  # Correct port mapping
    volumes:
      - ./frontend:/frontend
    command: npm run dev