version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: gunicorn auth.wsgi:application --bind 0.0.0.0:8000

  web:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    command: serve -s dist -l 5173