# Generated by Django 5.0.6 on 2024-06-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
