# Generated by Django 5.0.6 on 2024-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('regular', 'regular'), ('premium', 'premium'), ('ultime', 'ultime')], default='regular', max_length=20),
        ),
    ]
