# Generated by Django 5.0.6 on 2024-07-16 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_jpy', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_gbp', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_cny', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
