# Generated by Django 5.0.6 on 2024-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('regular', 'regular'), ('premium', 'premium'), ('ultimate', 'ultime')], default='regular', max_length=20),
        ),
    ]
