# Generated by Django 5.0.6 on 2024-07-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usercurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
