# Generated by Django 5.0.6 on 2024-07-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pendingtransactions'),
        ('users', '0012_alter_customuser_plan'),
    ]

    operations = [
    ]
