# Generated by Django 5.0.6 on 2024-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_contactusmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusmessages',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='contactusmessages',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
