# Generated by Django 5.0.6 on 2024-07-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20240714_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('tier1', 'regular'), ('tier2', 'premium'), ('tier3', 'ultimate')], default='regular', max_length=20),
        ),
    ]
