# Generated by Django 5.0.6 on 2024-07-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_pendingusersupdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingusersupdates',
            old_name='nom',
            new_name='current_nom',
        ),
        migrations.RenameField(
            model_name='pendingusersupdates',
            old_name='prenom',
            new_name='current_prenom',
        ),
    ]
