# Generated by Django 5.0.6 on 2024-07-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_nom_pendingusersupdates_current_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingusersupdates',
            name='tmp_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
