# Generated by Django 5.0.6 on 2024-07-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_pendingusersupdates_tmp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
