# Generated by Django 5.0.6 on 2024-07-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
